#!/bin/sh
rm -rf /usr/share/enigma2/GlamourAuraBerry
echo "                                                                   "
echo "Glamour Aura Berry skin was successfully removed from your receiver"
echo "                                                                   "
echo "The GUI of your receiver is now rebooting....                      "
sleep 2
init 4 && sleep 2 && init 3
