#!/bin/sh
if [ -f /tmp/GlamourAuraBerry/skin.xml ]; then
	rm -rf /usr/share/enigma2/GlamourAuraBerry/
	mv /tmp/GlamourAuraBerry /usr/share/enigma2/
fi
echo "                                                                                 "
echo "Glamour Aura Berry main files installed, now linking common files to main skin..." 
cp -Rs /usr/share/enigma2/GlamourAuraFHD/* /usr/share/enigma2/GlamourAuraBerry 2>/dev/null
echo "                                                                              "
echo "Glamour Aura Berry skin is now successfully installed on your receiver        "
echo "                         Enjoy!!!                                             "
