#!/bin/sh
if [ -f /tmp/GlamourAuraBerry/skin.xml ]; then
  rm -rf /usr/share/enigma2/GlamourAuraBerry/
  mv /tmp/GlamourAuraBerry /usr/share/enigma2/
fi
echo "                                                                                  "
echo "Glamour Aura Berry skin for OpenPLI is now successfully installed in your receiver"
echo "                             Enjoy!!!                                             "
