#!/bin/sh
rm -rf /usr/share/enigma2/GlamourAuraBerry
echo "                                                                   "
echo "Glamour Aura Berry skin was successfully removed from your receiver"