#!/bin/sh
echo "                                   *******                                  "
echo "                         ******               *****                         "
echo "                    ****                            ****                    "
echo "                 ***                                     ***                "
echo "               **     GLAMOUR AURA BERRY SKIN FOR OPENPLI   **              "
echo "                            a skin by MCelliotG                             "
echo "                                                                            "
echo "                                                                            "
echo "                         ***** DISCLAIMER ****                              "
echo "Glamour Aura Berry skin requires a minimal dual core CPU @ 751Mhz.          "
echo "Glamour Aura Berry is NOT guaranteed to work on slower or older receivers.  "
echo "                                                                            "
echo "                                                                            "
echo "                                                                            "
echo "                                                                            "
echo "Checking if a previous version of Glamour Aura Berry skin is installed"
if [ -f /usr/share/enigma2/GlamourAuraBerry/skin.xml ]; then
    cp -R /usr/share/enigma2/GlamourAuraBerry/ /tmp
    rm -rf /usr/share/enigma2/GlamourAuraBerry
    rm -rf /usr/lib/enigma2/python/Components/Converter/Glam*
    rm -rf /usr/lib/enigma2/python/Components/Renderer/Glam*
    echo "                                               "
    echo "Previous GlamourAuraBerry skin installation    "
    echo "    was found and removed successfully!        "
    echo "                                               "
fi
echo "                                                     "
echo "Glamour Aura Berry skin is now being installed...    "
echo "                                                     "
