#!/bin/sh
echo "                             *******                          "
echo "                       ******       *****                     "
echo "                  ****                   ****                 "
echo "               ***                            ***             "
echo "             **     GLAMOUR AURA BERRY SKIN      **           "
echo "                     a skin by MCelliotG                      "
echo "                                                              "
echo "                                                              "
echo "             *********    DISCLAIMER      *********           "
echo "Glamour Aura Berry skin requires a minimal CPU @ 751 Mhz."
echo "Glamour Aura Berry is NOT guaranteed to work on slower or older receivers."
echo "                                             "
echo "                                             "
echo "                                             "
echo "                                             "
echo "Checking if a previous version of Glamour Aura Berry skin is installed..."
if [ -f /usr/share/enigma2/GlamourAuraBerry/skin.xml ]; then
    cp -R /usr/share/enigma2/GlamourAuraBerry/ /tmp
    rm -rf /usr/share/enigma2/GlamourAuraBerry
    echo "                                             "
    echo "Previous Glamour Aura Berry skin installation"
    echo "    was found and removed successfully!      "
    echo "                                             "
fi
echo "                                                 "
echo "Glamour Aura Berry skin is now being installed..."
echo "                                                 "
