#!/bin/sh
echo "                                                               "
echo "Glamour Aura Berry skin is now being removed from your receiver"
echo "                                                               "
